config/routes.rb
Rails.application.routes.draw do

  resources :welcomes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcomes#index'

  get 'home/console'

  resources :articles do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article

end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "tetraceratops", password: "Templ@te#2017", except: [:index, :show]

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article, class: 'form-group') do |f| %>
    <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>

    <div class="actions" style="margin: 10px 0;">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles Index Page</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3">Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<span>
  <% @articles.inspect %>
</span>
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="commenter">
  <strong>Commenter:</strong>
  <span><%= comment.commenter %></span>
</div>

<div class="comment">
  <strong>Comment:</strong>
  <p><%= comment.body %></p>
</div>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment], class: "btn btn-primary", method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

<style type="text/css">
  .commenter span {
    color: red;
    margin: 0 10px;
  }
  .comment p {
    color: gray;
    margin: 10px 20px;
    display: inline-block;
  }
</style>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], class: 'form-group') do |f| %>
    <p>
      <%= f.label :commenter %>
      <%= f.text_field :commenter, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :body %>
      <%= f.text_area :body, cols: 20, rows: 15, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-primary' %>
    </p>

<% end %>

app/views/layouts/_footer.html.erb
<!-- START FOOTER -->
<div class="container footer">
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
      <h4>Navigation</h4>
      <ul class="navigation">
        <li><a href="#">Homepage</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Contac Us</a></li>
        <li><a href="#">Your Cart</a></li>
        <li><a href="#">Login</a></li>
      </ul>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <h4>My Account</h4>
      <ul class="navigation">
        <li><a href="#">My Account</a></li>
        <li><a href="#">Order History</a></li>
        <li><a href="#">Wish List</a></li>
        <li><a href="#">Newsletter</a></li>
      </ul>
    </div>
    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
      <p class="logo"><img src="/images/logo.png" class="site_logo" alt=""></p>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. the  Lorem Ipsum has been the industry's standard dummy text ever since the you.</p>
      <br/>
      <span class="social_icons">
        <a class="facebook" href="#">Facebook</a>
        <a class="twitter" href="#">Twitter</a>
        <a class="skype" href="#">Skype</a>
        <a class="vimeo" href="#">Vimeo</a>
      </span>
    </div>
  </div>
</div>

<div class="container footer-copyright">
  <span>&copy;2017 Tetraceratops team  All right reserved.</span>
</div>

<!-- END FOOTER -->

app/views/layouts/_header.html.erb
<!-- BEGIN HEADER -->
<div id="top-bar" class="container" role="navigation">

  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-10 col-xs-8 col-lg-offset-0 col-md-offset-0 col-sm-offset-1 col-xs-offset-0">
      <div class="input-group">
        <input type="text" class="form-control search-query" placeholder="Search...">
        <i class="icon-search search-tool"></i>
      </div>
    </div>

    <div class="col-lg-8 col-md-8 col-sm-10 col-xs-4 col-lg-offset-0 col-md-offset-0 col-sm-offset-1 col-xs-offset-0">
      <div class="pull-right navbar-inverse" role="navigation">
        <div class="item-content">
          <div class="">
            <button type="button" class="navbar-toggle navigation-btn" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">切换导航</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav">
              <li><a href="#">My Account</a></li>
              <li><a href="#">Checkout</a></li>
              <li><a href="#">Login</a></li>
              <li class="last-one"><a href="#">Sign up</a></li>
            </ul>
          </div>

        </div>
      </div>
    </div>

  </div>
</div>
<!-- END HEADER -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="author" content="tetraceratops-team">
    <meta name="keyword" content="tetraceratops">
    <meta name="description" content="tetraceratops team will make our life better and better">
    <link rel="shortcut icon" href="/favicon.ico">

    <title><%= Tetraceratops::Configuration['name'] %></title>


    <%= csrf_meta_tag %>
    <%= action_cable_meta_tag %>


    <%= stylesheet_link_tag    'application' %>


    <%= javascript_include_tag 'application' %>

    <style type="text/css">

    </style>
  </head>

  <!-- BEGIN BODY -->
  <body>

    <!--[if lt IE 7]>
    <p class="browsehappy">您的浏览器<strong>版本过低</strong>. 请<a href="http://browsehappy.com/">更新您的浏览器</a>.</p>
    <![endif]-->

    <!-- header -->
    <%= render partial: 'layouts/header' %>

    <!-- wrapper -->
    <%= render partial: 'layouts/wrapper' %>

    <!-- footer -->
    <%= render partial: 'layouts/footer' %>

  </body>

</html>

app/views/welcomes/_form.html.erb
<%= form_for(welcome) do |f| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcomes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcomes.each do |welcome| %>
      <tr>
        <td><%= welcome.name %></td>
        <td><%= welcome.age %></td>
        <td><%= link_to 'Show', welcome %></td>
        <td><%= link_to 'Edit', edit_welcome_path(welcome) %></td>
        <td><%= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Welcome', new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @welcome.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @welcome.age %>
</p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>